Minor changes to ShardMaterial
GallowsDove/FoxyMachines pull request #73
Opened 2023-07-16 03:51 UTC by JustAHuman-xD

What changed:
- When  a player does not have an active quest it will now also send a message to the player instead of only not consuming the shard
- Changed the message sent when resetting the quest to better match the new message added

2023-07-16 11:18 UTC, GallowsDove requested changes

2023-07-16 11:18 UTC, GallowsDove commented on src/main/java/me/gallowsdove/foxymachines/implementation/materials/ShardMaterial.java
> +                p.sendMessage(this.color + "You have no active quest!");
I think a better message would be something like "you should check your quest with /foxy quest first!". After that, there should be no point at which one doesn't have a quest I believe

2023-07-16 17:22 UTC, JustAHuman-xD commented
This has now been tested 👍

2023-08-01 18:58 UTC, GallowsDove approved these changes

2023-08-01 18:59 UTC, merged